# Generated by Django 4.2.3 on 2023-09-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sname', models.CharField(max_length=100)),
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('semail', models.EmailField(max_length=254)),
            ],
        ),
    ]
